# Section3: Basics: Data Types
[Course](https://www.udemy.com/course/former-python-mega-course-build-10-real-world-applications/learn/lecture/34362574#overview)
## List types
Lists are known as compound data types data structures, every data type has its own sintax. Lists are assigned by [].<br>
We can use range objects converted to lists to generate a ranged list.<br>
By using the dir("datatype") function, we can see a list of all the classes attributes
___
## Dictionary Types
Dicts are assigned by {}. Where dcit items are made up of key, value pairs. Access dicts values using their keys.
___
## Tuples
Tuples are assinged by (). They are immutable data types, much quicker than lists but not modifiable. You can have a list in a tuple and mutate the list, but you cannot mutate the tupple itself.
___
## Slicing lists
Can use negative indexing. Remember it is [x:y), and strings use the same indexing. so list[2] and string[2] work the same way.

In [9]:
def mean(value):
    if isinstance(value, dict):
        the_mean = sum(value.values()) / len(value)
    else:
        the_mean = sum(value) / len(value)
    return the_mean

In [10]:
student_grades = {
                    "Marry": 9.1,
                    "Sim": 8.8,
                    "John":7.5
                 }

In [11]:
mean(student_grades)

8.466666666666667

In [12]:
help(dict.values)

Help on method_descriptor:

values(...)
    D.values() -> an object providing a view on D's values



# Section 6: User Inputs

In [13]:
def weather_condition():
    user_temp = float(input())
    if user_temp > 7:
        return "Warm"
    else:
        return "Cold"

In [14]:
weather_condition()

ValueError: could not convert string to float: 'f'

In [1]:
user_input = input("Enter you name: ")
message = f"Hello {user_input}"
print(message)

Hello Brendan


In [2]:
def greet():
    user_name = input("Enter your name: ")
    return f"Hello {user_name}"

greet()

'Hello Nrenda'

In [3]:
def greet(name):
    return f"Hi {name.title()}"

greet("harry")

'Hi Harry'

# Setion 7: Loops

In [4]:
monday_temps = [9.1,8.8,7.6]
for temps in monday_temps:
    print(int(temps))

9
8
7


In [5]:
# Loop over the phone_numbers values and in each loop print out the phone number, but with '00' instead of '+'. In other words, your code should output:
phone_numbers = {"John Smith": "+37682929928", "Marry Simpons": "+423998200919"}

for values in phone_numbers.values():
    print(values.replace("+", "00"))

0037682929928
00423998200919


In [6]:
# While loops with breaks and continue
username = ''

# while username != 'pypy':
#     username = input("Enter username: ")

while True:
    username = input("Enter username: ")
    if username == 'pypy':
        break #break moves the cursor out of the loop
    else:
        continue #continue moves the cursor to the begining of the loop


KeyboardInterrupt: Interrupted by user

# Section 8: Simple program

In [7]:
def sentence_maker(phrase):
    phrase = phrase.lower()
    capitalized = phrase.capitalize()
    interrogatives = ("how", "what", "why")
    punctuations = ("!", ",", ".", "?")

    while capitalized.endswith(punctuations):
        capitalized = capitalized[:-1]
    
    if phrase.startswith(interrogatives):
        return f"{capitalized}?"
    else:
        return f"{capitalized}."

def user_text():
    results = []
    output = ""

    while True:
        user_input = input("Ma se kind: ")
        if user_input == "\end":
            break
        else: 
            temp = sentence_maker(user_input)
            results.append(temp)

    # for i in results:
    #     output += f"{sentence_maker(i)} "
    
    return " ".join(results).rstrip()



In [8]:
tests = ["why you ma?????????!!!!!!!!", "how jou ma", "what jou ma", "test jou ma."]

for test in tests:
    print(sentence_maker(test))

Why you ma?
How jou ma?
What jou ma?
Test jou ma.


In [10]:
help(str.strip)

Help on method_descriptor:

strip(self, chars=None, /)
    Return a copy of the string with leading and trailing whitespace removed.
    
    If chars is given and not None, remove characters in chars instead.



# Section 9: List Comprehensions

In [ ]:
# Simple list comprehension
temps = [221, 234, 340, 230]
new_temps = [temp / 10 for temp in temps]
new_temps

[22.1, 23.4, 34.0, 23.0]

In [ ]:
# List comprehension with if conditional
temps = [221, 234, 340, -9999, 230]
new_temps = [temp / 10 for temp in temps if temp != -9999]
new_temps

[22.1, 23.4, 34.0, 23.0]

In [ ]:
#Define a function that takes as a parameter a list that contains both integers and strings and returns the list containing only the integers. For example, if I called your function with foo([99, 'no data', 95, 94, 'no data']) it should return [99, 95, 94].
data = [99, 'no data', 95, 94, 'no data']
def clean(data):
    return [i for i in data if isinstance(i, int)]


In [ ]:
clean(data)

[99, 95, 94]

In [ ]:
#Define a function that takes as parameter list of numbers and returns the list containing only the numbers that are greater than 0. For example, I called your function with foo([-5, 3, -1, 101]) it should return [3, 101].
test = [-5, 3, -1, 101]
def greater_0(lst):
    return [i for i in lst if i > 0]

greater_0(test)

[3, 101]

## List comprehension if-else conditional
General structure is `[variable for variable in data]` <br>
If conditional: `[variable for variable in data if condition]`<br>
If-else conditional: `[variable if condition else condition for variable in data]`<br>

In [ ]:
# List Comprehension If-Else Conditional
temps = [221, 234, 340, -9999, 230]
new_temps = [i if i != -9999 else 0 for i in temps]
new_temps

[221, 234, 340, 0, 230]

In [ ]:
# Define a function that takes as parameter a list that contains both numbers and strings and returns the same list but with zeros instead of strings. For example, I called your function with foo([99, 'no data', 95, 94, 'no data']) it should return [99, 0, 95, 94, 0].
test = [99, 'no data', 95, 94, 'no data']
def str_int(data):
    return [i if isinstance(i, int) else 0 for i in data]

str_int(test)

[99, 0, 95, 94, 0]

In [ ]:
# Define a function that takes as parameter a list that contains decimal numbers as strings and returns the sum of those numbers
test = ['1.2', '2.6', '3.3']
def convert_sum(lst):
    return sum([float(i) for i in lst])

convert_sum(test)

7.1

# Section 10: More Functions

In [ ]:
# Implements a function that takes two strings as parameters, concatenates them, and returns the result.
def concat(a, b):
    return str(a) + str(b)

tests = [(1, 2), ("jou", "ma")]
for a, b in tests:
    print(concat(a, b))


12
jouma


Creating functions with n-lengths non-keyword arguments. Use *args as the parameter

In [ ]:
# args are returned as a tuple
def mean(*args):
    return args

mean(4, 3, "a", "hoe")

(4, 3, 'a', 'hoe')

In [ ]:
def mean(*args):
    return sum(args) / len(args)

mean(5, 4, 3, 2, 1, 5,6,3,2, 1, 5.6)

3.4181818181818184

In [ ]:
#Define a function that takes an indefinite number of strings as parameters and returns a list containing all the strings in UPPERCASE and sorted alphabetically.
def upper_sort(*args):
    return sorted([string.upper() for string in args])

upper_sort("k", "z", "y")

['K', 'Y', 'Z']

Creating a function with indefinite key word arguments. Use **kwargs.

In [ ]:
def mean(**kwargs):
    return kwargs

# mean(1, 2, 3) # will return error
mean(a=1, b=2, c=3) # returns a dict

{'a': 1, 'b': 2, 'c': 3}

## Cheatsheet: More on Functions
In this section, you learned that:

Functions can have more than one parameter:

```
def volume(a, b, c):
    return a * b * c
```
Functions can have default parameters (e.g. coefficient):

```
def converter(feet, coefficient = 3.2808):
    meters = feet / coefficient
    return meters
 
print(converter(10))
Output: 3.0480370641306997
```

Arguments can be passed as non-keyword (positional) arguments (e.g. a) or keyword arguments (e.g. b=2 and c=10):

```
def volume(a, b, c):
    return a * b * c
 
print(volume(1, b=2, c=10))
```
An *args parameter allows the  function to be called with an arbitrary number of non-keyword arguments:

```
def find_max(*args):
    return max(args)
print(find_max(3, 99, 1001, 2, 8))
Output: 1001
```

A **kwargs parameter allows the function to be called with an arbitrary number of keyword arguments:

```
def find_winner(**kwargs):
    return max(kwargs, key = kwargs.get)
 
print(find_winner(Andy = 17, Marry = 19, Sim = 45, Kae = 34))
Output: Sim
```

Here's a summary of function elements:
![](https://img-c.udemycdn.com/redactor/raw/2019-07-24_19-07-36-0d306e1785ef65d50aeb204567dfb62f.png)


# Section 11: File Processing
Cursor concept, when you open a file a cursor object is created at the beginning of the file. When you use the file.read() method, the cursor is moved to the end of the file.<br>
To re-use the file object, store the opening of the file in a variable and call and recall the variable. This way the cursor does not affect the code.

In [ ]:
my_file = open("./files/fruits.txt")
my_file.read()
my_file.read() # the cursor is at teh end of the file therefore an empty string is printed
my_file.close()

In [ ]:
my_file = open("./files/fruits.txt")
content = my_file.read()
print(content)
print(content)
my_file.close()

pear
apple
orange
mandarin
watermelon
pomegranate

pear
apple
orange
mandarin
watermelon
pomegranate



We need to close the file otherwise it remains open in RAM. A better way to handle the opening and closing of files is with the `with` keyword. The `with` context manager will close the file implicitly

In [ ]:
with open("./files/fruits.txt") as my_file:
    content = my_file.read()

print(content)

pear
apple
orange
mandarin
watermelon
pomegranate



In [ ]:
help(open)

Help on built-in function open in module io:

open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
    Open file and return a stream.  Raise OSError upon failure.
    
    file is either a text or byte string giving the name (and the path
    if the file isn't in the current working directory) of the file to
    be opened or an integer file descriptor of the file to be
    wrapped. (If a file descriptor is given, it is closed when the
    returned I/O object is closed, unless closefd is set to False.)
    
    mode is an optional string that specifies the mode in which the file
    is opened. It defaults to 'r' which means open for reading in text
    mode.  Other common values are 'w' for writing (truncating the file if
    it already exists), 'x' for creating and writing to a new file, and
    'a' for appending (which on some Unix systems, means that all writes
    append to the end of the file regardless of the current seek position

In [ ]:
# The "w" argument is used to write to a file, file contents will be overwritten
with open("./files/vegetables.txt", "w") as my_file:
    my_file.write("Tomato\nCucumber\nOnion\n")
    my_file.write("Garlic\n")

print(content)

6


In [ ]:
# Read the bear.txt file, and print out the first 90 characters of its content.
with open("./files/bear.txt", "r") as bear_file:
    context = bear_file.read()

print(context[:91])

The American black bear (Ursus americanus) is a medium-sized bear native to North America. 


In [ ]:
# Define a function that gets a single string character and a filepath as parameters and returns the number of occurences of that character in the file.

def open_count_chars(char, filepath):
    with open(filepath) as read_file:
        data = read_file.read()
    
    return data.count(char)

print(open_count_chars("e", "./files/bear.txt"))


56


In [ ]:
# Use Python to create a file with name file.txt and write the text snail there.

with open("./files/file.txt", "w") as open_file:
    open_file.write("snail")

In [ ]:
# Create a first.txt file that contains the first 90 characters of bear.txt.
# Note that you should read the content of bear.txt with Python, extract its first 90 characters with Python, and write those characters in first.txt with Python.

with open("./files/bear.txt", "r") as open_file:
    data = open_file.read()

with open("./files/file.txt", "w") as open_file:
    open_file.write(data[:91])

Appending to files is done with the `a` keyword argument.

In [ ]:
with open("./files/vegetables.txt", "a") as open_file:
    open_file.write("\nOkra")

With the `+` argument we can append and then read the file.

In [ ]:
with open("./files/vegetables.txt", "a+") as open_file:
    open_file.write("\nEggplant")
    open_file.seek(0)
    content = open_file.read()

print(content)# nothing is printed as the cursor is at the end of the file, apply the seek method to move the cursor to the beginnng of the file

Tomato
Cucumber
Onion
Garlic
Okra

Eggplant


In [ ]:
# Append the text of bear1.txt to bear2.txt. In other words, bear2.txt should contain its text and the text of bear1.txt after that.
with open("./files/bear1.txt", "r") as open_file:
    data = open_file.read()

with open("./files/bear2.txt", "a") as open_file:
    open_file.write(data)




In [ ]:
#Copy n-times (E)
with open("./files/data.txt", "r+") as open_file:
    data = open_file.read()
    for i in range(2):
        open_file.write(data)

with open("./files/data.txt", "r") as open_file:
    data = open_file.read()
    
print(data)


1.3,1.5
2.3, 2.7                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

In [ ]:
help(open)

Help on built-in function open in module io:

open(file, mode='r', buffering=-1, encoding=None, errors=None, newline=None, closefd=True, opener=None)
    Open file and return a stream.  Raise OSError upon failure.
    
    file is either a text or byte string giving the name (and the path
    if the file isn't in the current working directory) of the file to
    be opened or an integer file descriptor of the file to be
    wrapped. (If a file descriptor is given, it is closed when the
    returned I/O object is closed, unless closefd is set to False.)
    
    mode is an optional string that specifies the mode in which the file
    is opened. It defaults to 'r' which means open for reading in text
    mode.  Other common values are 'w' for writing (truncating the file if
    it already exists), 'x' for creating and writing to a new file, and
    'a' for appending (which on some Unix systems, means that all writes
    append to the end of the file regardless of the current seek position

# Section 12: Modules

In [9]:
import time
import pandas as pd

for i in range(1):
    if os.path.exists("files/temps_today.csv"):
        data = pd.read_csv("files/temps_today.csv")
        print(data.mean()["st1"])
    else:
        print("File not found")
        




22.125


# Section 13: Pandas

In [13]:
os.listdir("files/supermarkets/") # use os.listdir to view files in directory

['supermarkets-commas.txt',
 'supermarkets-semi-colons.txt',
 'supermarkets.csv',
 'supermarkets.json',
 'supermarkets.xlsx']

In [16]:
df1 = pd.read_csv("files/supermarkets/supermarkets.csv")
df2 = pd.read_json("files/supermarkets/supermarkets.json")

In [18]:
df3 = pd.read_excel("files/supermarkets/supermarkets.xlsx", sheet_name= 0)
df3

ID          Address           City             State Country  \
0   1     3666 21st St  San Francisco          CA 94114     USA   
1   2   735 Dolores St  San Francisco          CA 94119     USA   
2   3      332 Hill St  San Francisco  California 94114     USA   
3   4     3995 23rd St  San Francisco          CA 94114     USA   
4   5  1056 Sanchez St  San Francisco        California     USA   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   

  Supermarket Name  Number of Employees  
0          Madeira                    8  
1      Bready Shop                   15  
2      Super River                   25  
3       Ben's Shop                   10  
4          Sanchez                   12  
5       Richvalley                   20

In [20]:
df3 = pd.read_csv("files/supermarkets/supermarkets-commas.txt")
df4 = pd.read_csv("files/supermarkets/supermarkets-semi-colons.txt", sep=";")
df4

ID          Address           City             State Country          Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA       Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA   Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA   Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA    Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA       Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA    Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [22]:
# Setting Index values
df5 = df3.set_index("ID")
df5

Address           City             State Country         Name  \
ID                                                                          
1      3666 21st St  San Francisco          CA 94114     USA      Madeira   
2    735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
3       332 Hill St  San Francisco  California 94114     USA  Super River   
4      3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
5   1056 Sanchez St  San Francisco        California     USA      Sanchez   
6   551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

    Employees  
ID             
1           8  
2          15  
3          25  
4          10  
5          12  
6          20

In [23]:
# Geocode library for generating long/lat co-ordinates from an address
from geopy.geocoders import ArcGIS
nom = ArcGIS()

In [29]:
n = nom.geocode("3995 23rd St, San Francisco, CA 94114") # returns a location data type from an address
print(n.latitude, n.longitude)
type(n)

37.75292099814533 -122.43170295955227


geopy.location.Location

In [34]:
df = pd.read_csv("files/supermarkets/supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [35]:
df["Address"] = df["Address"]+", "+df["City"]+", "+df["State"]+", "+df["Country"]
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [36]:
df["Coordinates"] = df["Address"].apply(nom.geocode)
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [37]:
df["Latitude"] = df["Coordinates"].apply(lambda x: x.latitude if x != None else None)

In [41]:
df["Longitude"] = df["Coordinates"].apply(lambda x: x.longitude if x != None else None)

In [42]:
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756632 -122.429411  
1  (735 Dolores St, San Francisco, California, 94...  37.757829 -122.425373  
2  (332 Hill St, San Francisco, California, 94114...  37.755845 -122.428813  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921 -122.431703  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132 -122.430006  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582 -122.433234

In [58]:
# OpenCV is an image processing library
import cv2
import numpy as np

In [46]:
im_g = cv2.imread("files/smallgray.png", 0) #image read method 0 - grayscale , 1-rgb
print(im_g) # prints a numpy array of the colours of the pixels in the array
im_c = cv2.imread("files/smallgray.png", 1)
im_c

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [52]:
# MultiDimensional array slicing
print(im_g.shape, im_c.shape)
print(im_g)
im_g[0:2, 2:4]

(3, 5) (3, 5, 3)
[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


array([[104, 121],
       [255, 255]], dtype=uint8)

In [57]:
# iterating through arrays
print(im_g)
for i in im_g:
    print(i) #will print the rows

for i in im_g.T:
    print(i) # print columns

for i in im_g.flat:
    print(i) # print values individually

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]
[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]
187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [60]:
# stacking arrays
im_g_stacked = np.hstack((im_g, im_g)) # takes a tuple of arrays to stack them horizontally
print(im_g, im_g_stacked)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]] [[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [61]:
im_g_stacked = np.vstack((im_g, im_g)) # takes a tuple of arrays to stack them vertical
print(im_g, im_g_stacked)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]] [[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]
